- .gitignore
> Change to ignore local docker compose manifest

- .gitignore
> One at a time, change the docker local path

- requirements.txt
Reverts ccnmtl/metricsmentor#145
> Revert "Bump faker from 24.0.0 to 24.1.0"

- requirements.txt
Reverts ccnmtl/metricsmentor#148
> Revert "Revert "Bump faker from 24.0.0 to 24.1.0""

- README.md
- buildspec-staging.yml
- buildspec.yml
- docker-compose.yml
Adding `--no-cache` in the buildspec.yml
> Update build spec file

- media/js/src/scatterPlot.jsx
- media/js/src/simulationOne.jsx
- package-lock.json
- package.json
* add temp csv export to random values
* switch the slope and intercept (bug)
> Fix intercept and slope

- media/js/src/scatterPlot.jsx
- media/js/src/simulationOne.jsx
- media/scss/_base.scss
- media/scss/_simulation.scss
- media/scss/_topnav.scss
- media/scss/main.scss
- metricsmentor/templates/base.html
- metricsmentor/templates/main/simulation_dashboard.html
- metricsmentor/templates/registration/login.html
This PR is for the vanilla responsive layout for Sim1, for viewport sizes equal&smaller than SM, and equal&larger than MD. I'll continue working on the smoothness of it, but I'd like to have this up first before it gets too big.
> ERD-108: Basic responsive layout for Sim1

- media/js/src/simulationOne.jsx
- media/js/src/simulationOneQuiz.jsx
New variable is also included in the graph data.
> Input for user to choose a value for null hypothesis

- media/js/src/simulationOne/simulationOne.jsx
I'm leaving the input forms for t-value at the moment, let's get this one right first
> Fixed the t-value calculation, changed the size of katex fraction font-size

- media/js/src/simulationOne/hypothesisTest.jsx
- media/js/src/simulationOne/multipleChoiceQuestion.jsx
- media/js/src/simulationOne/quiz.jsx
- media/js/src/simulationOne/simulationOneQuiz.jsx
Takeaway question after completion of three alt hypothesis
> Erd 92- Add Takeaway question

- media/js/src/simulationOne/simulationOne.jsx
Inviting you to review for approval. Don't merge, just approve when done.
> Apply styling to coefficient section

- media/js/src/simulationOne/scatterPlot.jsx
- media/js/src/simulationOne/simulationOne.jsx
- media/scss/_simulation.scss
I added the graph equation in graphspace, in `simulationOne.jsx`, which means it is not directly associated to the scatter plot. Let me know if it is better to have it in `scatterPlot.jsx` and how I can go about doing that.
> Erd 140 equation in graphspace

- media/js/src/simulationOne/simulationOneQuiz.jsx
- media/scss/_listset.scss
- media/scss/main.scss
This is the list of alternative hypothesis with the "do this" buttons. Don't worry about how it looks yet, I just want this up for now to do the flow for the workspace
> Alt hypothesis list, trying this out for size

- media/js/src/simulationOne/scatterPlot.jsx
- media/js/src/simulationOne/simulationOne.jsx
- media/js/src/simulationOne/simulationOneQuiz.jsx
- metricsmentor/urls.py
* This also fixes that bug I found and just cleaning up a couple of things
> Only allowed 3D when 2D is done

- media/js/src/simulationOne/scatterPlot.jsx
The range of numbers is now from -100 to 100. We can change this to fit our needs.
I've also adjusted the scatterplot so that it centers the points a little more
> adjust plot range

- metricsmentor/templates/flatpages/default.html
Just some formatting changes to bring the flat page in line with the styling found in LogicLearner.
> About Page

- media/js/src/simulationOne/simulationOne.jsx
@zmustapha just a thought. Change this Save Graph Data button to Start Quiz? Or something else?
> Change button

- media/js/src/simulationOne/graphCoefficientsSection.jsx
- media/js/src/simulationOne/simulationOne.jsx
- media/scss/_base.scss
- media/scss/_forms.scss
- media/scss/_simulation.scss
- media/scss/_typography.scss
- media/scss/main.scss
Starting out refined changes to the workspace. This PR is up to the "Resulting Graphs Coefficients"
> ERD-105: Style changes to the workspace up to graph coefficient

- metricsmentor/main/views.py
I think our issue was in the wrong formula. I was using calculations of t-distribution but this needs normal distribution.
> Use normal distribution

- media/scss/_base.scss
- metricsmentor/templates/base.html
Reverts ccnmtl/metricsmentor#310
> Revert "Added usability survey link on topnav"

- media/scss/_base.scss
- metricsmentor/templates/base.html
Reverts ccnmtl/metricsmentor#312
> Revert "Revert "Added usability survey link on topnav""

- media/js/src/simulationOne/nullHypothesisSection.jsx
- media/js/src/simulationOne/simulationOne.jsx
- media/js/src/simulationOne/simulationOneQuiz.jsx
- metricsmentor/main/views.py
> Fix the rounding

- metricsmentor/main/views.py
The absolute value function here was throwing things off
> Fix pvalue bug

- media/js/src/simulationOne/quiz.jsx
Only show comparison with the absolute value of t when the hypothesis is two tailed.
> Fix absolute t

- media/js/src/multipleChoiceQuestion.jsx
- media/js/src/simulationOne/graphCoefficientsSection.jsx
- media/js/src/simulationOne/hypothesisTest.jsx
- media/js/src/simulationOne/nullHypothesisSection.jsx
- media/js/src/simulationOne/pvalueComponent.jsx
- media/js/src/simulationOne/quiz.jsx
- media/js/src/simulationOne/scatterPlot.jsx
- media/js/src/simulationOne/simulationIntro.jsx
- media/js/src/simulationOne/simulationOne.jsx
- media/js/src/simulationOne/simulationOneQuiz.jsx
This is working. Just needs some refactoring. Very much brute force version here.
> 3d Implementation 

- media/js/src/simulationOne/nullHypothesisSection.jsx
Reverts ccnmtl/metricsmentor#360
> Revert "Disable null hypothesis for now"

- media/js/src/simulationOne/nullHypothesisSection.jsx
Reverts ccnmtl/metricsmentor#363
> Revert "Revert "Disable null hypothesis for now""

- media/js/src/simulationTwo/ControlVariable.jsx
- media/js/src/simulationTwo/Variables2.jsx
- media/js/src/simulationTwo/scatterPlot2.jsx
- media/js/src/simulationTwo/simulationTwo.jsx
After rendering the values once I’ve realized that I don’t need to run them again. They are static, so I refactored with the hard-coded the values. If we want to double check or add new data all we need to do is `POST` the data to `/calc_regression/` or `/calc-multi_regression/`. No need to do all of those calculations every time.
> Multiple regression lines are now availible for Sim 2

- buildspec-staging.yml
- buildspec.yml
Update to installation of `cdefense` CLI to get 1.38.4 from AWS Parameter Store
> Update clouddefense parameters buildspec

- media/js/src/dashboard.jsx
* Remove this restriction for sim 2
> Remove superuser restriction

- media/js/src/simulationTwo/simulationTwo.jsx
I'll fill out the functionality for the button in the other PR once this is mergeded and I can rebase it.
> Sim 2: Start over button

- media/js/src/dataAttr.jsx
- media/js/src/multipleChoiceQuestion2.jsx
- media/js/src/simulationTwo/controlVariable.jsx
- media/js/src/simulationTwo/simulationTwo.jsx
- media/js/src/simulationTwo/variables.jsx
Filled in data from https://docs.google.com/document/d/1xRaZghWptGu0uwLDauQ-LWuduyX7REwT/edit#heading=h.gjdgxs including the correlation values for each control variable.
> Added Feedback to Sim 2

- media/js/src/multipleChoiceQuestion2.jsx
- media/js/src/simulationTwo/simulationTwo.jsx
Tweaked a few things to match the Figma Workflow
> Added Feedback to Sim 2, part 2

- media/js/src/simulationTwo/controlVariable.jsx
- media/js/src/simulationTwo/learningGoals.jsx
- media/js/src/simulationTwo/simulationTwo.jsx
- media/js/src/simulationTwo/variables.jsx
Evan, here is the PR for some of the instruction text that I've made so far. It's not completed, but enough for you to make that dataset-dependent text blocks
> Some MentorVoice text

- media/js/src/dashboard.jsx
- media/js/src/dataAttr.jsx
- media/js/src/simulationTwo/controlVariable.jsx
- media/js/src/simulationTwo/variables.jsx
- media/js/src/utils.jsx
I'm PRing this stage of changes first because I don't want the PRs to be too big
> More sim2 instructions

- media/js/src/multipleChoiceQuestion.jsx
- media/js/src/simulationOne/criticalValue.jsx
- media/js/src/simulationOne/hypothesisTest.jsx
- media/js/src/simulationOne/nullHypothesisSection.jsx
- media/js/src/simulationOne/pvalueComponent.jsx
- media/js/src/simulationOne/quiz.jsx
- media/js/src/simulationOne/simulationOne.jsx
- media/js/src/simulationOne/simulationOneQuiz.jsx
* A bit of a mess. But it's functional for now.
> Revised workflow

- media/js/src/simulationOne/hypothesisTest.jsx
- media/js/src/simulationOne/nullHypothesisSection.jsx
- media/js/src/simulationOne/simulationOne.jsx
- media/js/src/simulationOne/simulationOneQuiz.jsx
This reverts commit 245d7000fb34ab21ff25188661b9ab72d5713b78.
> Revert "disable controls when alpha is selected"

- media/js/src/multipleChoiceQuestion2.jsx
- media/js/src/simulationTwo/controlVariable.jsx
- media/js/src/simulationTwo/quiz2.jsx
- media/js/src/utils.jsx
- media/scss/_listset.scss
First batch of changes in styling. I want to keep the PRs small for easier reviews
> Sim2 buttons spacing revision

- media/js/src/simulationTwo/simulationTwo.jsx
Don't you love/hate it when the fix is just one line of code?
> Clear choice in onContinue()

- media/js/src/multipleChoiceQuestion.jsx
- media/js/src/utils.jsx
@Evan-CTL Just letting you know in case you need it, I've been using this function to do the answer comparison regardless of html elements. I've moved it into the utils file
> Move function into utils

- media/js/src/app.jsx
- media/js/src/dashboard.jsx
Reverts ccnmtl/metricsmentor#537
> Revert "Open sim 2 - Only Merge at 4pm"

- media/js/src/simulations/simulation1/simulationIntro.jsx
I am not sure when we lost this button and I don't remember where or what it looked like so I'm tagging you here @zmustapha
> Add glossary button back in

- package-lock.json
- package.json
Reverts ccnmtl/metricsmentor#646
> Revert "Bump plotly.js from 2.35.0 to 3.0.0"

- package-lock.json
- package.json
Reverts ccnmtl/metricsmentor#667
> Revert "Bump eslint from 8.57.1 to 9.20.0"

- media/js/src/app.jsx
- media/js/src/containers/dashboard.jsx
Reverts ccnmtl/metricsmentor#674
> Close to students - 5PM

- media/js/src/app.jsx
- media/js/src/containers/dashboard.jsx
Reverts ccnmtl/metricsmentor#710
> Revert "Open sim 2 to students - Merge at 4pm"

- media/js/src/simulations/simulation3/skedasticityLearning.jsx
- media/js/src/simulations/simulation3/skedasticityPlot.jsx
Data points still aren't perfect but I figured this is a good point to commit
> More work on the learning part

- media/js/src/simulations/simulation3/multicollinearityApply.jsx
- media/js/src/simulations/simulation3/simulationThree.jsx
- media/js/src/simulations/simulation3/skedasticityReal.jsx
- media/js/src/simulations/simulation3/whatIsHeteroskedasticity.jsx
- media/js/src/simulations/simulation3/whatIsMulticollinearity.jsx
Play with this locally and see if you like the behavior. I can match it for Multicollinearity in another PR
> Integrate Review button switch for Heteroskedasticity

- media/js/src/Table.jsx
For now just the component. We'll implement after Tuesday
> Table component

- media/js/src/simulations/simulation3/simulationThree.jsx
- media/js/src/simulations/simulation4/polynomial.json
- media/js/src/simulations/simulation4/polynomialGraph.jsx
- media/js/src/simulations/simulation4/simulationFour.jsx
* Just building out preliminary steps to sim 4
* Made the graph a little more standard to what we have elsewhere
* And some small refactors
> Build out more of sim 4

- media/js/src/simulations/simulation4/polynomialGraph.jsx
- media/js/src/simulations/simulation4/simulationFour.jsx
- media/js/src/simulations/simulation4/whatAreNonlinearRegs.jsx
* mysteryRegLine was changed so that you can have multiple regression lines turned on for the mystery data
* Added mystery data checkbox with regression checkboxes
TODO: Bring in actual values for the formulas
> Implement mystery checkbox

- cypress/e2e/4.Sim3/sim3.cy.js
- media/js/src/simulations/simulation3/heteroskedTakeaway.jsx
- media/js/src/simulations/simulation3/multicollinearityTakeaway.jsx
- media/js/src/simulations/simulation3/simulationThree.jsx
Only display back to dashboard when takeaways on both sims have been complete
> Dashboard button logic

- media/js/src/StepProgressButton.jsx
- media/js/src/simulations/simulation4/simulationFour.jsx
* This collapses the learning section when you move on to real dataset
* I've also added a component for the Continues and Review buttons
> Collapse section

- media/js/src/simulations/simulation4/polynomialTakeaway.jsx
- media/js/src/simulations/simulation4/simulationFour.jsx
> Add takeaways Polynomials

- media/js/src/simulations/simulation4/realDataPolynomials.jsx
- media/js/src/simulations/simulation4/simulationFour.jsx
Also removed the `console.log()`
> Continue button appears after the mini quiz is completed
